<?php




/**
Hook_menu()
https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_menu/7.x
*/

function shiny_menu(){
    $items['admin/config/shiny'] = array(
        'title' => 'Shiny',
        'description' => 'Adjust shiny options',
        'position' => 'right',
        'page callback' => 'system_admin_menu_block_page',
        'access arguments'=> array('administer site configuration'),
        'file' => 'system.admin.inc',
        'file path' => drupal_get_path('module', 'system'),
    );

    $items['admin/config/shiny/settings'] = array (
        'title' => 'Shiny Settings',
        'description' => 'Adjust shiny settings',
        'page callback' => 'drupal_get_form',
        //go to shiny.admin.inc
        'page arguments'=> array('shiny_admin_settings'),
        'access arguments'=> array('administer site configuration'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'shiny.admin.inc',
    );


    $items['shinyApi'] = array(
        'title' => 'Shiny API gateway: register new block',
        'page callback' => 'shiny_api_handler',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
        'file' => 'shiny.api.inc',
        
    );
    //page callback for post request
    $items['shinyApi/register'] = array(
        'title' => 'Shiny API gateway: register new block',
        'page callback' => 'shiny_register_new_block',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
        'file' => 'shiny.api.inc',
        
    );



    return $items;

}





/*
    hook_block 
    Create custom block for shiny
*/
function shiny_block_info() {
  $blocks['shiny'] = array(
    // The name that will appear in the block list.
    'info' => t('Shiny main content'),
    // Default setting.
    //https://api.drupal.org/api/drupal/includes!common.inc/group/block_caching/7.x
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 * 
 * Prepares the contents of the block.
 */
function shiny_block_view($delta = '') {

    //delta is the name of blocks passed in from drupal

        switch ($delta) {
            case 'shiny':
                //delegate the job to shiny.block.inc
                module_load_include('inc', 'shiny', 'shiny.block');
                $block = shiny_block_content_generate();
                break;
        }

        return $block;
  
}








