<?php

/*
    hook_block 
    Create custom block for shiny
*/
function shiny_block_info() {
  $blocks['shiny'] = array(
    // The name that will appear in the block list.
    'info' => t('Shiny main content'),
    // Default setting.
    //https://api.drupal.org/api/drupal/includes!common.inc/group/block_caching/7.x
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}




/**
 * Implements hook_block_view().
 * 
 * Prepares the contents of the block.
 */
function shiny_block_view($delta = '') {

    //path to modules libs folder
    //TODO: \ for linux based OS ? 
    $libs_path = drupal_get_path('module', 'shiny') . '/libs/';

    //delta is the name of blocks passed in from drupal
    //can also use if($delta == 'name of the block')
        switch ($delta) {
        case 'shiny':
            $block['subject'] = t('Shiny Main Content');
            /*
                Customize the block content   
            */
            $block['content'] = array(

                '#attached' => array (

                    'js' => array(
                        //angularjs
                        $libs_path.'js/angular.min.js',
                        //shiny angular app
                        $libs_path.'app/app.module.js',
                        $libs_path.'app/shiny/shiny.module.js',
                        $libs_path.'app/shiny/shiny.component.js',
                        $libs_path.'app/shiny/shiny.service.js',

                    ),// end js array

                    'css' => array()
                ), //attached 
                '#markup' => generate_block_content($libs_path)
                // '#markup' => t('shiny block main content asdfsdf')
            );
            
        return $block;
  }
  
}


// /*
//     Test
// */
function generate_block_content($libs_path){
    $html_content = '';

    $html_content .= $libs_path. '

    <p> This is the main content of shiny block</p>

    <div ng-app="devApp"> <shiny> </shiny> </div>

    ';

    return $html_content;
}











































/** Hook_menu*/

// function shiny_menu(){
//     $items['admin/config/shiny'] = array(
//         'title' => 'Shiny Visualization',
//         'description' => 'Configure Shiny visualization options.',
//         'position' => 'right',
//         'weight' => -5,
//         'page callback' => 'system_admin_menu_block_page',
//         'access arguments' => array('administer site configuration'),
//         'file' => 'system.admin.inc',
//         'file path' => drupal_get_path('module', 'system')
//         );

//     $items['admin/config/shiny/settings'] = array(
//         'title' => 'Shiny Settings',
//         'description' => 'Configure Shiny visualization Settings.',
//         'page callback' => 'system_admin_menu_block_page',
//         'access arguments' => array('administer site configuration'),
//         'type' => MENU_NORMAL_ITEM,
//         'file' => 'shiny.admin.inc'
//         );

// }

// /* hook_on_load() */

// function shiny_node_load($nodes, $types){
//     global $user;

//     //check to see if the person viewing the node is the author. 
//     //if not hide the module
//     foreach ($nodes as $node ) {
//         if($user->uid != $node->uid){
//             unset($node->shiny);
//         }
//     }
// }