<?php

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function current_posts_help($path, $arg) {
  switch ($path) {
    case "admin/help#current_posts":
      return '' . t("Displays links to nodes created on this date") . '';
      break;
  }
} 

/**
 * Implements hook_block_info().
 */
function current_posts_block_info() {
  $blocks['current_posts'] = array(
    // The name that will appear in the block list.
    'info' => t('Current posts'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}


/**
 * Implements hook_block_view().
 * 
 * Prepares the contents of the block.
 */
function current_posts_block_view($delta = '') {
  switch ($delta) {
    case 'current_posts':
      $block['subject'] = t('Current posts');

      $block['content'] = t('<p> this is cnrrent posts block con tent</p>');
      // if (user_access('access content')) {
      //   // Use our custom function to retrieve data.
      //   $result = current_posts_contents();
      //   // Array to contain items for the block to render.
      //   $items = array();
      //   // Iterate over the resultset and format as links.
      //   foreach ($result as $node) {
      //     $items[] = array(
      //       'data' => l($node->title, 'node/' . $node->nid),
      //     ); 
      //   }
      //  // No content in the last week.
      //   if (empty($items)) {
      //     $block['content'] = t('No posts available.');  
      //   } 
      //   else {
      //     // Pass data through theme function.
      //     $block['content'] = theme('item_list', array(
      //       'items' => $items));
      //   }
      // }
    return $block;
  }
  
}