<?php

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function current_posts_help($path, $arg) {
  switch ($path) {
    case "admin/help#current_posts":
      return '' . t("Displays links to nodes created on this date") . '';
      break;
  }
} 

/**
 * Implements hook_block_info().
 */

/*
There is a way to include the JS you need and still 
enable caching for the html. To do this, following these instructions.
https://api.drupal.org/api/drupal/modules%21block%21block.api.php/function/hook_block_view/7.x
*/

function current_posts_block_info() {
  $blocks['current_posts'] = array(
    // The name that will appear in the block list.
    'info' => t('Current posts'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}


/**
 * Implements hook_block_view().
 * 
 * Prepares the contents of the block.
 */
function current_posts_block_view($delta = '') {

    $libs = drupal_get_path('module', 'current_posts');
    $js_libs = $libs . '/libs/js/current.js';

        switch ($delta) {
        case 'current_posts':
          $block['subject'] = t('Current posts');

          $block['content'] = array(

            '#attached' => array ($js_libs),
            '#markup' => t($js_libs)
            );
        return $block;
  }
  
}

