<?php


/**
Hook_menu()
*/

function annotate_menu(){
    $items['admin/config/annotate'] = array(
        'title' => 'Node annotation',
        'description' => 'Adjust node annotation options',
        'position' => 'right',
        'page callback' => 'system_admin_menu_block_page',
        'access arguments'=> array('administer site configuration'),
        'file' => 'system.admin.inc',
        'file path' => drupal_get_path('module', 'system'),
    );

    $items['admin/config/annotate/settings'] = array (
        'title' => 'Annotation Settings',
        'description' => 'Adjust node annotation settings',
        'page callback' => 'drupal_get_form',
        'page arguments'=> array('annotate_admin_settings'),
        'access arguments'=> array('administer site configuration'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'annotate.admin.inc',
    );

    return $items;

}